application/pay_parking/pay_parking/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.edit import CreateView
from users.forms import CustomUserCreationForm


admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=CustomUserCreationForm,
            success_url=reverse_lazy('parking:list'),
        ),
        name='registration',
    ),
    path('user/', include('users.urls')),
    path('payments/', include('paying.urls')),
    
    path('', include('parking.urls')),
]

application/pay_parking/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

application/pay_parking/templates/includes/header.html
<header id="header">
  <div id="branding">
    <div id="site-name">
      <a href="{% url 'parking:list' %}">Сервис платных парковок</a>
    </div>
  </div>
  {% block usertools %}
    <div id="user-tools">
      <strong>{{ user.first_name }} {{ user.second_name }} {{ user.third_name|default_if_none:'' }}</strong>
      {% if user.is_authenticated %}
        <a href="{% url 'users:profile' %}">Профиль</a> /
        {% if user.is_staff %}
          <a href="{% url 'admin:index' %}">Администрирование</a> /
        {% endif %}
        <form id="logout-form" method="post" action="{% url 'logout' %}">
          {% csrf_token %}
          <button type="submit">Выйти</button>
        </form>
      {% else %}
        <a href="{% url 'login' %}">Войти</a> /
        <a href="{% url 'registration' %}">Регистрация</a> /
      {% endif %}
      {% include 'admin/color_theme_toggle.html' %}
    </div>
  {% endblock %}
</header>