application/pay_parking/pay_parking/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.edit import CreateView
from users.forms import CustomUserCreationForm


admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=CustomUserCreationForm,
            success_url=reverse_lazy('parking:list'),
        ),
        name='registration',
    ),
    path('user/', include('users.urls')),
    path('payments/', include('paying.urls')),
    
    path('', include('parking.urls')),
]

application/pay_parking/paying/urls.py
from django.urls import path
from . import views

app_name = 'paying'
urlpatterns = [
    path('list/', views.user_payments, name='list'),
    path('create/<slug:parking_id>/', views.create_payment, name='create'),
    path('create/<slug:parking_id>/confirm/', views.confirm_create, name='confirm_create'),
]

application/pay_parking/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

application/pay_parking/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django_mongodb_backend.models import EmbeddedModel


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('Email is required')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        return self.create_user(email, password, **extra_fields)


class EmbeddedUser(EmbeddedModel):
    email = models.EmailField(verbose_name='Электронная почта')
    first_name = models.CharField(max_length=30, verbose_name='Имя')
    second_name = models.CharField(max_length=30, verbose_name='Фамилия')
    third_name = models.CharField(
        max_length=30, verbose_name='Отчество', null=True
    )
    created_at = models.DateField('Регистрация')
    is_staff = models.BooleanField(
        default=False, verbose_name='Статус персонала')

    def full_name(self):
        third_name = self.third_name if self.third_name is not None else ''
        return f'{self.first_name} {self.second_name} {third_name}'

    full_name.short_description = 'Фио пользователя'

    def __str__(self):
        third_name = self.third_name if self.third_name is not None else ''
        staff = '<br>Сотрудник' if self.is_staff is not None else ''
        return f'{self.first_name} {self.second_name} {third_name}' \
            f'<br>{self.email}' \
            f'{staff}'


class User(AbstractBaseUser):
    email = models.EmailField(unique=True, verbose_name='Электронная почта')
    first_name = models.CharField(max_length=30, verbose_name='Имя')
    second_name = models.CharField(max_length=30, verbose_name='Фамилия')
    third_name = models.CharField(
        max_length=30, verbose_name='Отчество', null=True, blank=True
    )
    objects = UserManager()
    is_staff = models.BooleanField(
        default=False, verbose_name='Статус персонала')
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name='Последнее редактирование',
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name='Регистрация',
    )
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'second_name']

    def __str__(self):
        third_name = self.third_name if self.third_name is not None else ''
        return f'{self.first_name} {self.second_name} {third_name}'

    def has_perm(self, *args, **kwargs):
        return self.is_staff

    def has_module_perms(self, *args, **kwargs):
        return self.is_staff

    def save(self, *args, **kwargs):
        if self.id:
            self.payments.update(
                user_detail=EmbeddedUser(
                    email=self.email,
                    first_name=self.first_name,
                    second_name=self.second_name,
                    third_name=self.third_name,
                    is_staff=self.is_staff,
                    created_at=self.created_at,
                )
            )
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'Пользователи'

application/pay_parking/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import get_user_model
from pay_parking.forms import FormWithFormsets, StatisticsForm

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        labels = {
            "email": "Электронная почта",
            "third_name": "Отчество (если есть)"
        }
        model = User
        fields = ('email', 'first_name', 'second_name',
                  'third_name', 'password1', 'password2')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'second_name', 'third_name')

class UserAdminForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'second_name', 'third_name', 'password', 'is_staff')

class UserFilterForm(FormWithFormsets):
    first_name = forms.CharField(max_length=30, required=False, label='Имя')
    second_name = forms.CharField(
        max_length=30, required=False, label='Фамилия')
    third_name = forms.CharField(
        max_length=30, required=False, label='Отчество')
    email = forms.CharField(max_length=254, required=False, label='')
    is_staff = forms.BooleanField(required=False, label='')
    min_created_at = forms.DateTimeField(
        required=False, label='От',
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"})
    )
    max_created_at = forms.DateTimeField(
        required=False, label='До',
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"})
    )
    min_updated_at = forms.DateTimeField(
        required=False, label='От',
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"})
    )
    max_updated_at = forms.DateTimeField(
        required=False, label='До',
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"})
    )
    min_last_login = forms.DateTimeField(
        required=False, label='От',
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"})
    )
    max_last_login = forms.DateTimeField(
        required=False, label='До',
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"})
    )

    class Meta:
        fieldsets = (
            ('Фио', {
                'fields': ('first_name', 'second_name', 'third_name')
            }),
            ('Email', {
                'fields': ('email', )
            }),
            ('Сотрудник', {
                'fields': ('is_staff', )
            }),
            ('Регистрация', {
                'fields': ('min_created_at', 'max_created_at')
            }),
            ('Последнее редактирование', {
                'fields': ('min_updated_at', 'max_updated_at')
            }),
            ('Последний вход', {
                'fields': ('min_last_login', 'max_last_login')
            })
        )
        

application/pay_parking/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import UserForm

@login_required
def edit_profile(request):
    instance = request.user
    form = UserForm(request.POST or None, instance=instance)
    context = {'form': form}
    if form.is_valid():
        form.save()
        return redirect('users:profile')
    return render(request, 'users/user.html', context)


@login_required
def profile(request):
    return render(request, 'users/profile.html')

application/pay_parking/templates/users/profile.html
{% extends 'admin/base_site.html' %}
{% load i18n static %}

{% block content %}
  <h1>Страница пользователя</h1>
  <fieldset class="module aligned">
    <div class="form-row"><div class="flex-container">
        <label>Электронная почта: </label><div class="readonly">{{ user.email }}</div>
    </div></div>
    <div class="form-row"><div class="flex-container">
        <label>Фио: </label><div class="readonly">{{ user.first_name }} {{ user.second_name }} {{ user.third_name|default_if_none:'' }}</div>
    </div></div>
    <div class="form-row"><div class="flex-container">
      <label>Последнее редактирование: </label><div class="readonly">{{ user.updated_at }}</div>
    </div></div>
    <div class="form-row"><div class="flex-container">
      <label>Роль: </label><div class="readonly">{% if user.is_staff %}Сотрудник{% else %}Пользователь{% endif %}</div>
    </div></div>
    <div class="form-row"><div class="flex-container">
      <label>Оплаты: </label><div class="readonly"><a class="viewlink" href="{% url 'paying:list' %}">Оплаты</a></div>
    </div></div>
  </fieldset>
  <a class="changelink" href="{% url 'users:edit_profile' %}">Редактировать профиль</a>
{% endblock %}

{% block breadcrumbs %}
  <div class="breadcrumbs">
    Страница пользователя
  </div>
{% endblock %}

application/pay_parking/templates/users/user.html
{% extends 'admin/base_site.html' %}
{% load i18n static %}

{% block content %}
  <h1>Редактирование профиля</h1>
  <div class="flex-container">
    <form method="post">
      {% if form.errors and not form.non_field_errors %}<p class="errornote">Пожалуйста, исправьте ошибку ниже.</p>{% endif %}
      {{ form.non_field_errors}}
      {% csrf_token %}
      <fieldset class="module aligned">
          {% for field in form %}
            <div class="form-row">
              {{ field.errors }}
              <div class="flex-container">{{ field.label_tag }} {{ field }}</div>
              <div class="help">{{ field.help_text }}</div>
            </div>
          {% endfor %}
      </fieldset>
      <input type="hidden" name="next" value="{{ next }}" />
      <div class="submit-row">
        <input type="submit" class="default" value="Изменить" />
      </div>
    </form>
  </div>
{% endblock %}

{% block breadcrumbs %}
  <div class="breadcrumbs">
    <a href="{% url 'users:profile' %}">Страница пользователя</a>
    &rsaquo; Редактирование профиля
  </div>
{% endblock %}